# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy on GithubPage

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

# å®šä¹‰ä¸€ä¸ªä½œä¸š
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    # è¿è¡Œå™¨ï¼Œä½¿ç”¨ GitHub æ‰˜ç®¡çš„ ubuntu-latest
    runs-on: ubuntu-latest
    # æ­¥éª¤
    steps:
      # æ£€å‡ºä»“åº“ä»£ç 
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      # è®¾ç½® node ç¯å¢ƒï¼Œä½¿ç”¨ node18
      - name: Setup Node ğŸ”§
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # å®‰è£…ä¾èµ–
      - name: Install Dependencies ğŸ”§
        run: npm install

      # æ„å»ºé¡¹ç›®
      - name: Build ğŸ”§
        run: npm run build

      # éƒ¨ç½²åˆ° GitHub Pagesï¼Œä½¿ç”¨ç¬¬ä¸‰æ–¹æ“ä½œ
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
