# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy on GithubPage

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

# å®šä¹‰ä¸€ä¸ªä½œä¸š
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    # è¿è¡Œå™¨ï¼Œä½¿ç”¨ GitHub æ‰˜ç®¡çš„ ubuntu-latest
    runs-on: ubuntu-latest
    # æ­¥éª¤
    steps:
      # æ£€å‡ºä»“åº“ä»£ç 
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          pnpm ci --frozen-lockfile
          pnpm run build

      # éƒ¨ç½²åˆ° GitHub Pagesï¼Œä½¿ç”¨ç¬¬ä¸‰æ–¹æ“ä½œ
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
